mariadb:
  primary:
    persistence:
      size: 4Gi

    resources:
      limits:
        cpu: 400m
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 50Mi

  secondary:
    persistence:
      size: 4Gi

    resources:
      limits:
        cpu: 400m
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 50Mi
