mariadb:
  enabled: true

  auth:
    rootPassword: TO_BE_SET
    createDatabase: true
    database: callweb
    username: callweb
    password: TO_BE_SET

  initdbScripts:
    my_init.sql: |
      GRANT ALL PRIVILEGES ON *.* TO 'callweb'@'%';

  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      slow_query_log=0
      slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
      long_query_time=10.0
      innodb_page_size=32k
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_520_ci
      plugin-load=server_audit=server_audit.so
      server_audit_logging=ON
      server_audit_file_path=/opt/bitnami/mariadb/logs/server_audit.log
      server_audit_events='query,table'
      server_audit_file_rotate_size=10000000 
      server_audit_file_rotations=10

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=utf8mb4
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

      [mysql]
      default-character-set=utf8mb4

    existingConfigmap: ""

    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

    persistence:
      size: 2Gi

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 50Mi

    extraEnvVars:
      - name: TZ
        value: "America/Vancouver"

  architecture: replication

  secondary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      size: 2Gi
    extraEnvVars:
      - name: TZ
        value: "America/Vancouver"
