mariadb:
  primary:
    persistence:
      size: 50Mi
    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 50Mi

  architecture: standalone
