mariadb:
  primary:
    persistence:
      size: 400Mi

    resources:
      limits:
        cpu: 800m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi

  architecture: standalone
