mariadb:
  primary:
    persistence:
      size: 4Gi

    resources:
      limits:
        cpu: 800m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi

  secondary:
    persistence:
      size: 4Gi

    resources:
      limits:
        cpu: 800m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi
