apiVersion: v2
name: callweb-survey
description: A Helm chart for deploying CallWeb solution

type: application

version: 0.2.7

appVersion: 1.0.0

dependencies:
  - name: generic-api
    version: 0.2.7
    repository: https://bcgov.github.io/helm-charts
    alias: callweb
