apiVersion: v2
name: callweb-survey
description: A Helm chart for deploying CallWeb solution

type: application

version: 0.2.6

appVersion: 1.0.0

dependencies:
  - name: generic-api
    version: 0.2.6
    repository: https://bcgov.github.io/helm-charts
    condition: callweb.enabled
    alias: callweb
