callweb:
  nameOverride: survey-test

  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 40

  resources:
    limits:
      cpu: 600m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi

  env:
    DB_HOST:
      value: mariadb-test
      secure: true

  extraContainers:
    s3-sync:
      env:
        MINIO_URI:
          value: http://minio-test:9000

  initContainers:
    s3-init:
      env:
        MINIO_URI:
          value: http://minio-test:9000
