callweb:
  nameOverride: survey-prod

  replicaCount: 2

  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 90
    targetCPUUtilizationPercentage: 40

  resources:
    limits:
      cpu: 600m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi

  env:
    DB_HOST:
      value: mariadb-prod
      secure: true

  extraContainers:
    s3-sync:
      env:
        MINIO_URI:
          value: http://minio-prod:9000

  initContainers:
    s3-init:
      env:
        MINIO_URI:
          value: http://minio-prod:9000
