callweb:
  nameOverride: survey-test

  resources:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

  extraContainers:
    www:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi

    s3-sync:
      env:
        MINIO_URI:
          value: http://minio-test:9000

  initContainers:
    s3-init:
      env:
        MINIO_URI:
          value: http://minio-test:9000
