callweb:
  resources:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi
  extraContainers:
    www:
      resources:
        limits:
          cpu: 100m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 100Mi
