backup:
  image:
    repository: docker.io/bcgovimages/backup-container-mariadb
    pullPolicy: IfNotPresent
    tag: 2.5.2

  backupConfig: |
    mariadb=mariadb-dev-primary:3306/callwebcw221003_roster
    mariadb=mariadb-dev-primary:3306/callwebcw221003_sandbox
    mariadb=mariadb-dev-primary:3306/callwebcwde_2022

    0 1 * * * default ./backup.sh -s
    0 4 * * * default ./backup.sh -s -v all

  config:
    - filename: 60-tweaks.cnf
      mountPath: /etc/my.cnf.d/60-tweaks.cnf
      contents: |
        [mysqld]
        innodb_page_size=32k
        datadir = /var/lib/mysql/data

  db:
    secretName: survey-dev-secrets
    usernameKey: db-username
    passwordKey: db-password

  env:
    DATABASE_SERVICE_NAME:
      value:
    ENVIRONMENT_FRIENDLY_NAME:
      value: "Maria DB Backups"

  persistence:
    backup:
      size: 4Gi
      mountPath: /backups/
      storageClassName: netapp-file-backup
      storageAccessMode: ReadWriteOnce

    verification:
      size: 2Gi
      mountPath: /var/lib/mysql/data
      storageClassName: netapp-block-standard
      storageAccessMode: ReadWriteOnce
