backup:
  db:
    secretName: survey-test-secrets

  backupConfig: |
    mariadb=mariadb-test-primary:3306/callwebcw221003_roster
    mariadb=mariadb-test-primary:3306/callwebcw221003_sandbox
    mariadb=mariadb-test-primary:3306/callwebcwde_2022

    0 1 * * * default ./backup.sh -s
    0 4 * * * default ./backup.sh -s -v all

  persistence:
    backup:
      size: 50Mi
    verification:
      size: 50Mi
