backup:
  db:
    secretName: survey-test-secrets

  backupConfig: |
    mariadb=mariadb-test:3306/callwebcw221003_roster
    mariadb=mariadb-test:3306/callwebcw221003_sandbox
    mariadb=mariadb-test:3306/callwebcwde_2022

    0 1 * * * default ./backup.sh -s
    0 4 * * * default ./backup.sh -s -v all

  persistence:
    backup:
      size: 50Mi
    verification:
      size: 100Mi

  config:
    - filename: 60-tweaks.cnf
      mountPath: /etc/my.cnf.d/60-tweaks.cnf
      contents: |
        [mysqld]
        innodb_page_size=32k
        datadir = /var/lib/mysql/data
        innodb_data_file_path=ibdata1:60M:autoextend
        innodb_buffer_pool_size = 48M
        innodb_additional_mem_pool_size = 2M
        innodb_log_file_size = 5M
        innodb_log_buffer_size = 8M
        innodb_flush_log_at_trx_commit = 1
        innodb_lock_wait_timeout = 50
