backup:
  db:
    secretName: survey-prod-secrets

  backupConfig: |
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_c_roster
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_p1
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_p2
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_p3
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_resume
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_roster
    mariadb=mariadb-prod-primary:3306/callweb2023_bcds_surveyassist

    0 1 * * * default ./backup.sh -s
    0 4 * * * default ./backup.sh -s -v all

  persistence:
    backup:
      size: 3Gi
    verification:
      size: 1Gi

  config:
    - filename: 60-tweaks.cnf
      mountPath: /etc/my.cnf.d/60-tweaks.cnf
      contents: |
        [mysqld]
        innodb_page_size=32k
        datadir = /var/lib/mysql/data
        innodb_data_file_path=ibdata1:40M:autoextend
        innodb_temp_data_file_path=ibtmp1:20M
        innodb_buffer_pool_size = 48M
        innodb_log_file_size = 5M
        innodb_log_buffer_size = 8M
        innodb_flush_log_at_trx_commit = 1
        innodb_lock_wait_timeout = 50
