name: deploy

# Were we can define the inputs that our action will accept
inputs:
  environment:
    required: true

runs:
  using: "composite"
  environment: "${{ inputs.environment }}"
  steps:
    - uses: actions/checkout@v3

    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: "4.6"

    - name: "Get Helm"
      shell: bash
      run: |
        curl -L -O https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz
        tar -xf helm-*-linux-amd64.tar.gz
        export PATH=$PATH:`pwd`/linux-amd64

    - name: Authenticate to silver and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        insecure_skip_tls_verify: true

        namespace: ${{ vars.OCP_LICENSE_PLATE }}-${{ inputs.environment }}

    - name: Report
      shell: bash
      run: |
        (echo '<pre>'; helm version; echo '</pre>') >> $GITHUB_STEP_SUMMARY
        (echo '<pre>'; helm list; echo '</pre>') >> $GITHUB_STEP_SUMMARY

    - name: "Deploy Solution"
      shell: bash
      run: |
        echo "${{ secrets.CONFIG }}" > .env
        set -a && . ./.env && set +a
        cat env.template.yaml | envsubst > .env.yaml

        HELM_ARGS="-n ${{ vars.OCP_LICENSE_PLATE }}-${{ inputs.environment }} --history-max 2 -f .env.yaml"

        helm dependency build charts/minio
        helm upgrade --install minio-${{ inputs.environment }} $HELM_ARGS ./charts/minio

        helm dependency build charts/mariadb
        helm upgrade --install mariadb-${{ inputs.environment }} $HELM_ARGS ./charts/mariadb

        helm dependency build charts/callweb-admin
        helm upgrade --install admin-${{ inputs.environment }} $HELM_ARGS ./charts/callweb-admin

        helm dependency build charts/callweb-survey
        helm upgrade --install survey-${{ inputs.environment }} $HELM_ARGS ./charts/callweb-survey

    - name: Post Upgrade Summary
      shell: bash
      run: |
        echo "### Post Upgrade Summary" >> $GITHUB_STEP_SUMMARY
        (echo '<pre>'; helm list -n ${{ vars.OCP_LICENSE_PLATE }}-${{ inputs.environment }}; echo '</pre>') >> $GITHUB_STEP_SUMMARY
