callweb:
  nameOverride: admin-prod

  resources:
    limits:
      cpu: 150m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 50Mi

  env:
    DB_HOST:
      value: mariadb-prod-primary
      secure: true

  extraContainers:
    s3-sync:
      env:
        MINIO_URI:
          value: http://minio-prod:9000

  initContainers:
    s3-init:
      env:
        MINIO_URI:
          value: http://minio-prod:9000
