name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      argocd_tag:
        description: 'Release tag for tenant-gitops-af9df1'
        required: true
        default: ''

env:
  ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "built!"
        echo "### Helm Manifest ${{ inputs.argocd_tag }}" >> $GITHUB_STEP_SUMMARY

  deploy-dev:
    name: "Deploy to dev"
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: publish
    steps:
    - name: Install argocd cli
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64

    - name: Deploy
      run: |
        echo "argocd list" >> $GITHUB_STEP_SUMMARY
        echo '\n```\n' >> $GITHUB_STEP_SUMMARY
        argocd --grpc-web app list >> $GITHUB_STEP_SUMMARY
        echo '\n```\n' >> $GITHUB_STEP_SUMMARY

  deploy-test:
    name: "Deploy to test"
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: [publish, deploy-dev]
    steps:
    - name: deploy
      run: |
        echo "deployed to test!"

  deploy-prod:
    name: "Deploy to prod"
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [publish, deploy-test]
    steps:
    - name: deploy
      run: |
        echo "deployed to prod!"
