name: Continuous Delivery

on:
  push:
    branches: [ main ]


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "built!"

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
    - name: deploy
      run: |
        echo "deployed to dev!"
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT        
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

  deploy-test:
    name: "Test of ${{ steps.step1.outputs.test }}"
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: [build-and-publish, deploy-dev]
    steps:
    - name: deploy
      run: |
        echo "deployed to test!"

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-test]
    steps:
    - name: deploy
      run: |
        echo "deployed to dev!"
