name: Continuous Delivery
run-name: CD Release ${{ inputs.argocd_tag }}

on:
  workflow_dispatch:
    inputs:
      argocd_tag:
        description: 'Release tag for tenant-gitops-af9df1'
        required: true
        default: ''

env:
  ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}

jobs:
  initiate:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "### Helm Manifest ${{ inputs.argocd_tag }}" >> $GITHUB_STEP_SUMMARY

  deploy-dev:
    name: "Deploy to dev"
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: initiate
    steps:
    - name: Install argocd cli
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
    - name: Deploy
      run: |
        echo "do a patch, sync by label, and then wait by label"
        (echo '<pre>'; argocd --grpc-web app list; echo '</pre>') >> $GITHUB_STEP_SUMMARY

  test-automation:
    name: "Test Automation"
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: [deploy-dev]
    steps:
    - name: deploy
      run: |
        echo "do test automation - consider it happy!"
        echo "Test automation not implemented yet" >> $GITHUB_STEP_SUMMARY

  deploy-test:
    name: "Deploy to test"
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: deploy-dev
    steps:
    - name: deploy
      run: |
        echo "deployed to test!"

  deploy-prod:
    name: "Deploy to prod"
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [test-automation, deploy-test]
    steps:
    - name: deploy
      run: |
        echo "deployed to prod!"
