name: Continuous Delivery
run-name: CD Release ${{ inputs.target_revision }} ${{ inputs.commit_note }}

on:
  workflow_dispatch:
    inputs:
      target_revision:
        description: "Revision from tenant-gitops-af9df1"
        required: false
        default: ""
      include_gateway:
        type: boolean
        description: "Deploy API Gateway configuration"
        default: false
      commit_note:
        description: "Commit note"
        required: false
        default: ""

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - name: Deploy
        uses: "./.github/templates/deploy"
        with:
          environment: dev
