name: Continuous Delivery
run-name: CD Release ${{ inputs.target_revision }} ${{ inputs.commit_note }}

on:
  workflow_dispatch:
    inputs:
      target_revision:
        description: "Revision from tenant-gitops-af9df1"
        required: false
        default: ""
      include_gateway:
        type: boolean
        description: "Deploy API Gateway configuration"
        default: false
      commit_note:
        description: "Commit note"
        required: false
        default: ""

jobs:
  initiate:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - name: build
        run: |
          echo "### Helm Manifest ${{ inputs.target_revision }}" >> $GITHUB_STEP_SUMMARY
          echo "https://github.com/bcgov-c/tenant-gitops-af9df1/releases/tag/${{ inputs.target_revision }}" >> $GITHUB_STEP_SUMMARY

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: "4.6"

      - name: Authenticate to silver and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true

          namespace: ${{ vars.OPENSHIFT_NAMESPACE }}

      - name: "Get Helm"
        run: |
          curl -L -O https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
          tar -xf helm-v3.4.2-linux-amd64.tar.gz
          export PATH=$PATH:`pwd`/linux-amd64

      - name: Report
        run: |
          (echo '<pre>'; helm list; echo '</pre>') >> $GITHUB_STEP_SUMMARY

      - uses: actions/checkout@v2
        with:
          repository: bcgov-c/tenant-gitops-af9df1
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.target_revision }}
          path: ./infra

      - name: "Deploy Solution"
        run: |
          cd infra
          echo "${{ secrets.CONFIG }}" > .env.yaml

          helm dependency build ./aps-gateway
          helm upgrade --install aps-gateway -n af9df1-tools --history-max 2 ./aps-gateway

          helm dependency build minio
          helm upgrade --install minio-dev --history-max 2 -f .env.yaml ./minio

          helm dependency build mariadb
          helm upgrade --install mariadb-dev --history-max 2 -f .env.yaml ./mariadb

          helm dependency build callweb-admin
          helm upgrade --install admin-dev --history-max 2 -f .env.yaml ./callweb-admin

          helm dependency build callweb-survey
          helm upgrade --install survey-dev --history-max 2 -f .env.yaml ./callweb-survey
