name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      argocd_tag:
        description: 'Release tag for tenant-gitops-af9df1'
        required: true
        default: ''

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "built!"
        echo "### Input ${{ inputs.logLevel }}" >> $GITHUB_STEP_SUMMARY

  deploy-dev:
    name: "Deploy to dev"
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
    - name: deploy
      run: |
        echo "deployed to dev!"
        echo "argocd sync apps for the dev apps"
        echo "### Deployed to dev ${GITHUB_REF#refs/*/} ${{github.ref_name}}" >> $GITHUB_STEP_SUMMARY

  deploy-test:
    name: "Deploy to test"
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: [build-and-publish, deploy-dev]
    steps:
    - name: deploy
      run: |
        echo "deployed to test!"

  deploy-prod:
    name: "Deploy to prod"
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-test]
    steps:
    - name: deploy
      run: |
        echo "deployed to prod!"
